# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-16 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
